### ISSUE TITLE
Change model temperature of existing conversation

### ISSUE THREAD

**Issue by ryansereno** [ivanfioravanti/chatbot-ollama#11]
<img width="862" alt="Screenshot 2023-10-08 at 4 11 07 PM" src="https://github.com/ivanfioravanti/chatbot-ollama/assets/81782870/7ab72880-c2a5-4418-ae3b-226f098110dc">

Language model  can be changed, but not temperature.
I can try to take a look at this this week, if it makes sense to you to have this ability.

**Comment by ivanfioravanti** [comment]
It would be nice to be able to change temperature after each message, but I think this will interfere with import/export feature. Usually I create a new chat with different tempearture and same prompt to be able to compare results.

**Comment by ryansereno** [comment]
okay makes sense, I figured there was an implementation reason
