### ISSUE TITLE
unable to change model

### ISSUE THREAD

**Issue by ivoryzh** [ivanfioravanti/chatbot-ollama#17]
I was using `ollama pull` to download new model, I can see the model in the dropdown menu, but they won't generate. (mistral works fine btw)

**Comment by ivanfioravanti** [comment]
Have you tried to change model to another one and try again? Sometimes I see that model change is not working properly

**Comment by thebadking** [comment]
I've replaced in the src every match of mistral:latest to the model I want and still it tries to fetch from mistral:latest, where is this encoded?

**Comment by ivoryzh** [comment]
> Have you tried to change model to another one and try again? Sometimes I see that model change is not working properly

Hi Ivan, thanks for your response. I think it works now (tested with llama2), I had to download mistral too, otherwise it will complain `[OllamaError: model 'mistral:latest' not found, try pulling it first] `
