### ISSUE TITLE
When I run the app, the chat bot doesn't reply and says : 'model 'mistral:latest' not found, try pulling it first'

### ISSUE THREAD

**Issue by Max-J-B123** [ivanfioravanti/chatbot-ollama#22]
I'm sure its something silly i'm missing.

I tried typing 'docker pull mistral:latest' but it said i didn't have permission

**Comment by jmcarlile** [comment]
I haven't tried anything yet, but just wanted to throw out my first idea. Have you tried using sudo and your system password?

**Comment by ivanfioravanti** [comment]
@Max-J-B123 try `ollama rum mistral:latest`

**Comment by herropaul** [comment]
> @Max-J-B123 try `ollama run mistral:latest`

confirming that running this first works: 

<img width="514" alt="Screenshot 2023-11-30 at 11 58 11 AM" src="https://github.com/ivanfioravanti/chatbot-ollama/assets/35973829/14b00fa5-b876-4945-99d4-26ef9dcf57cb">
<img width="1710" alt="Screenshot 2023-11-30 at 11 58 26 AM" src="https://github.com/ivanfioravanti/chatbot-ollama/assets/35973829/2691c604-0f08-483c-9772-9de5ce9a0922">

**Comment by herropaul** [comment]
> > > @Max-J-B123 try `ollama run mistral:latest`
> > 
> > 
> > confirming that running this first works:
> > <img alt="Screenshot 2023-11-30 at 11 58 11 AM" width="514" src="https://private-user-images.githubusercontent.com/35973829/287054176-14b00fa5-b876-4945-99d4-26ef9dcf57cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MDkyNjksIm5iZiI6MTcwMTQwODk2OSwicGF0aCI6Ii8zNTk3MzgyOS8yODcwNTQxNzYtMTRiMDBmYTUtYjg3Ni00OTQ1LTk5ZDQtMjZlZjlkY2Y1N2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA1MzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNjkyZTgzYTViNDg2NjRhY2IzYWNjYzNiZmFmY2VmYTQxZjMxYTk4OTMyZDc0MTcyNWFlZmUyMmI0NTczMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DYy9TJMDZoeylSgGWPNyyOER3FiePhN7JOapbugrOfQ"> <img alt="Screenshot 2023-11-30 at 11 58 26 AM" width="1710" src="https://private-user-images.githubusercontent.com/35973829/287054203-2691c604-0f08-483c-9772-9de5ce9a0922.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MDkyNjksIm5iZiI6MTcwMTQwODk2OSwicGF0aCI6Ii8zNTk3MzgyOS8yODcwNTQyMDMtMjY5MWM2MDQtMGYwOC00ODNjLTk3NzItOWRlNWNlOWEwOTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA1MzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0M2EwODE5ZTVjMDNkOGU3MWMzZjc0MTBmNzQ0MjFjMzg4Nzk3Yjk5MGNiMjM2NTBhMTI1ZmY0YTQ1ODRjY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yBuDCcSqHS7_-vOU3o7KE3A9A-KDHx-I4p4jEIb8G44">
> 
> Many thanks for the suggestion, it now works. It seems like to ensure the UI works smoothly, you have to download the default model (mistral:latest) (through ollama) even though you chose another model (e.g., llama2:latest) in the prompt. That's a bit of a weird behaviour..

Glad to hear it works on ur end! But yea i feel like the UI should prompt and check to see if the user has installed the models through ollama before using the chat

**Comment by Max-J-B123** [comment]
"ollama run mistral:latest" this command worked for me
