### ISSUE TITLE
Ollama API returned an error 404: 404 page not found

### ISSUE THREAD

**Issue by yinrong** [ivanfioravanti/chatbot-ollama#26]
ollama is working, but chatbot-ollama reports 404 error

```
docker run --rm -it -e OLLAMA_HOST="http://127.0.0.1:11434/" --net=host -e DEFAULT_MODEL=llama2 --name chatbot-ollama ghcr.io/ivanfioravanti/chatbot-ollama:main
```

![image](https://github.com/ivanfioravanti/chatbot-ollama/assets/4221569/e4ec4d67-690d-4792-8978-a84dcaf46434)
![image](https://github.com/ivanfioravanti/chatbot-ollama/assets/4221569/d54786e9-d440-493e-b6ac-5b5accfa0b53)

**Comment by Toasterbirb** [comment]
In my case removing the slash from the end of the `OLLAMA_HOST` URL fixed this issue. So in your case the variable would be `OLLAMA_HOST="http://127.0.0.1:11434"` instead of `OLLAMA_HOST="http://127.0.0.1:11434/"`

**Comment by ivanfioravanti** [comment]
@Toasterbirb is right! Great!
