### ISSUE TITLE
Unable to connect to model when ollama is hosted on a different server

### ISSUE THREAD

**Issue by AdirthaBorgohain** [ivanfioravanti/chatbot-ollama#4]
I am hosting ollama remotely in a server and trying to deploy the chatbot-ollama on a different server. Accordingly, I added the `OLLAMA_HOST` env variable pointing to the address of my ollama server.

When I start chatbot-ollama, when I input something in the GUI, in the logs it says 
` [OllamaError: stat /root/.ollama/models/manifests/registry.ollama.ai/library/llama2/latest: no such file or directory] {
 name: 'OllamaError'}`

Also, weirdly, I set the `DEFAULT_MODEL` env variable to `llama-2-70b-chat-nous-hermes` in my dockerfile but it is trying to search for `llama2` model? The `llama-2-70b-chat-nous-hermes` model is up and running on the ollama server btw (created from a Modelfile).

How do I fix this?

**Comment by ivanfioravanti** [comment]
Ok @AdirthaBorgohain here we are:

- let's assume IP of your server is 10.0.0.34 (so not exposing OLLAMA on 127.0.0.1)
- start ollama server with OLLAMA_HOST=10.0.0.34 ollama serve 
- add this to env.local file or env variable in your host (or pass it to DOCKER) OLLAMA_HOST="http://10.0.0.34:11434" 
- start with npm run dev or docker

This should do the trick. Please be aware that OLLAMA is exposed on http so traffic is in cleartext on the network.
Please let me know if this works.

**Comment by AdirthaBorgohain** [comment]
Ok so here's how I have setup:
- Say I have started the ollama server on 10.0.0.34
- I checked and verified from a different server that I can reach the ollama server
- I started chatbot-ollama on the different server and set two env variables: `DEFAULT_MODEL="mistral"` and `OLLAMA_HOST="http://10.0.0.34"`
- When the chatbot-ollama server start, I get some pings on the ollama server that says `/api/tags` which I guess means that the chatbot-ollama is able to reach the ollama-server
- In the chatbot-ollama UI, when I type in something as input, I get and error in the chatbot-ollama logs saying `.ollama/models/manifests/registry.ollama.ai/library/llama2/latest: no such file or directory] { name: 'OllamaError'}`. 

I believe there's an issue here. The servers are reachable it seems, if I change the default model to something else, it throws some issues? Because I want to run mistral here and it is trying to search for llama2. And also, why is chatbot-ollama searching for the model files on its own system when the actual ollama-server is running on a completely different server.

**Comment by ivanfioravanti** [comment]
No troubles at all, please try to run ollama run llama2:latest just to see if the presence of this default model will make a difference. I user Mistral too locally, it's so great!!!
/api/tags is the call used to retrive models. I've seen an issue that I reported that it seems that first call is always done with previously selected model.

Please let me know if it works in this way.

**Comment by AdirthaBorgohain** [comment]
Okay here's what I found.

Everything works if `llama2:latest` is already downloaded. If `llama2:latest` is not downloaded, the chatbot does not work. Even if `DEFAULT_MODEL` is set to `mistral`, it tries to find `llama2:latest` initially and fails if it does not find `llama2:latest`
So, I believe the behaviour when `DEFAULT_MODEL`  is set to some other model can be fixed?

**Comment by ivanfioravanti** [comment]
Thanks for the investigation! I'll check this in the weekend. I ver it's related to NextJS requiring NEXT_PUBLIC_ in front of DEFAULT_MODEL

**Comment by ivanfioravanti** [comment]
@AdirthaBorgohain this should be fix now. I removed the need for a default model, if it's defined in env.local and present in OLLAMA server it will be used, otherwise it should you any available model. 

@ryansereno I have removed your toast, no more needed, I hope 🤞
