### ISSUE TITLE
I get an error, but the service of ollama/ollama is running

### ISSUE THREAD

**Issue by she1110** [ivanfioravanti/chatbot-ollama#41]
}
 [TypeError: fetch failed] {
  cause:  [Error: getaddrinfo ENOTFOUND host.docker.internal] {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'host.docker.internal'
}

**Comment by ivanfioravanti** [comment]
@insunaa is right here.
