### ISSUE TITLE
CPU pegged to 100%

### ISSUE THREAD

**Issue by insunaa** [ivanfioravanti/chatbot-ollama#46]
Running the container is completely fine, but as soon as I open localhost:3000 in any graphical browser the tab pegs one CPU core to 100% and refuses to let go. I cannot scroll up with the scroll wheel, the site will immediately scroll back to the bottom (using the scrollbar at the side by hand works)
It feels like you don't sync to vblank or whatever so your site just tries to render as many frames as the CPU allows? Either way no sleep of any kind seems to happen, making the project almost unusable.

Unfortunately I'm not a web-dev, so even if I wish I could, I can't really help.

![image](https://github.com/ivanfioravanti/chatbot-ollama/assets/3718129/a24a62f8-27fc-4b84-a8aa-44db38b5348a)
maybe this profiler callstack helps some. probably not given the obfuscation.

**Comment by ivanfioravanti** [comment]
I tried to replicate but no luck, has anyone else faced the same problem?

**Comment by insunaa** [comment]
If it helps any, I've been using Linux with Wayland and an Nvidia GPU (which doesn't have implicit sync implemented, and doesn't receive an explicit sync either).
This does not occur with any other website tho, so I would be very skeptical to accept that as the reason

**Comment by TheNaman047** [comment]
Yup I faced this today, my chrome tab usage went to 100% cpu. FYI: Was running via docker container if it helps

**Comment by ivanfioravanti** [comment]
can you please try again with latest?

**Comment by insunaa** [comment]
Latest docker pull seems to have fixed both the scrolling issue and the CPU usage issue!
I think you can close the issue
