### ISSUE TITLE
no matching manifest for windows/amd64 10.0.22631

### ISSUE THREAD

**Issue by oceangle** [ivanfioravanti/chatbot-ollama#47]
Hi guys, when I use the docker command: docker run -p 3000:3000 ghcr.io/ivanfioravanti/chatbot-ollama:main to install the image, it showed the error:  no matching manifest for windows/amd64 10.0.22631 in the manifest list entries. What should I do? Thank you!

![issue](https://github.com/ivanfioravanti/chatbot-ollama/assets/32094486/00624b9a-8795-4445-ae12-df0aaf52aa71)

**Comment by ivanfioravanti** [comment]
Be sure you are using Linux containers and not Windows containers in Windows Docker configuration
